import type { ReaderType, ReaderTypeId } from './types';

export const readerTypes: Record<ReaderTypeId, ReaderType> = {
  dreamer: {
    id: 'dreamer',
    name: 'The Dreamer',
    adventureTitle: 'THE DREAMER',
    emoji: '🌙',
    description: 'You love magical worlds and stories full of wonder.',
    kidTagline: 'You love stories that feel like dreams come true!',
    likes: ['magical worlds', 'wonder & imagination', 'unforgettable characters'],
    recommendedCategories: ['📖 Fantasy stories', '📖 Fairy tales', '📖 Magical adventures'],
    tags: ['Fantasy', 'Fiction'],
    genreLabel: 'magical worlds',
    searchGenres: ['Fantasy', 'Magical Realism', 'Mythology'],
    searchMoods: ['Whimsical', 'Emotional', 'Hopeful'],
    searchQueries: ['fantasy magical', 'magical realism'],
    genres: [
      { name: 'Magical Worlds', emoji: '🏰', gradient: 'linear-gradient(135deg, #6b5ce7, #a78bfa)' },
      { name: 'Fairy Tales', emoji: '🧚', gradient: 'linear-gradient(135deg, #5f8d62, #a8c4a9)' },
      { name: 'Wonder Stories', emoji: '✨', gradient: 'linear-gradient(135deg, #4a7050, #7fa882)' },
      { name: 'Moonlit Tales', emoji: '🌙', gradient: 'linear-gradient(135deg, #2d4330, #5f8d62)' },
      { name: 'Enchanted Lands', emoji: '🦄', gradient: 'linear-gradient(135deg, #7c3aed, #c4b5fd)' },
    ],
  },
  adventurer: {
    id: 'adventurer',
    name: 'The Explorer',
    adventureTitle: 'THE EXPLORER',
    emoji: '🌎',
    description: 'You love discovering new places, ideas, and epic journeys.',
    kidTagline: 'You love discovering new places and ideas!',
    likes: ['big adventures', 'exploring new worlds', 'exciting quests'],
    recommendedCategories: ['📖 Adventure stories', '📖 Fantasy', '📖 Science'],
    tags: ['Adventure', 'Action'],
    genreLabel: 'adventures',
    searchGenres: ['Adventure', 'Action', 'Epic Fantasy'],
    searchMoods: ['Adventurous', 'Exciting', 'Epic'],
    searchQueries: ['adventure epic fantasy', 'survival quest'],
    genres: [
      { name: 'Epic Quests', emoji: '🗺️', gradient: 'linear-gradient(135deg, #f59e0b, #fbbf24)' },
      { name: 'Space Adventures', emoji: '🚀', gradient: 'linear-gradient(135deg, #1e2d20, #3b5940)' },
      { name: 'Survival Tales', emoji: '🏔️', gradient: 'linear-gradient(135deg, #4a7050, #7fa882)' },
      { name: 'Hero Journeys', emoji: '⚔️', gradient: 'linear-gradient(135deg, #2d4330, #5f8d62)' },
      { name: 'Wild Expeditions', emoji: '🌎', gradient: 'linear-gradient(135deg, #059669, #34d399)' },
    ],
  },
  detective: {
    id: 'detective',
    name: 'The Mystery Solver',
    adventureTitle: 'THE MYSTERY SOLVER',
    emoji: '🔎',
    description: 'You love puzzles, secrets, and cracking the case!',
    kidTagline: 'You love solving mysteries and finding clues!',
    likes: ['mystery cases', 'clever puzzles', 'surprise endings'],
    recommendedCategories: ['📖 Mystery stories', '📖 Detective tales', '📖 Puzzle books'],
    tags: ['Mystery', 'Thriller'],
    genreLabel: 'mysteries',
    searchGenres: ['Mystery', 'Thriller', 'Crime'],
    searchMoods: ['Mysterious', 'Suspenseful', 'Dark'],
    searchQueries: ['mystery thriller', 'crime detective'],
    genres: [
      { name: 'Mystery Cases', emoji: '🔎', gradient: 'linear-gradient(135deg, #1e2d20, #3b5940)' },
      { name: 'Secret Clues', emoji: '🧩', gradient: 'linear-gradient(135deg, #2d4330, #5f8d62)' },
      { name: 'Spooky Mysteries', emoji: '🕵️', gradient: 'linear-gradient(135deg, #4a7050, #7fa882)' },
      { name: 'Code Breakers', emoji: '🔐', gradient: 'linear-gradient(135deg, #3b5940, #6b7280)' },
      { name: 'Whodunit?', emoji: '❓', gradient: 'linear-gradient(135deg, #1e2d20, #2d4330)' },
    ],
  },
  romantic: {
    id: 'romantic',
    name: 'The Heart Reader',
    adventureTitle: 'THE HEART READER',
    emoji: '💕',
    description: 'You love stories about friendship, love, and big feelings.',
    kidTagline: 'You love stories that make your heart feel full!',
    likes: ['friendship stories', 'heartwarming tales', 'characters you cheer for'],
    recommendedCategories: ['📖 Friendship stories', '📖 Heartwarming tales', '📖 Feel-good books'],
    tags: ['Romance', 'Fiction'],
    genreLabel: 'heartwarming stories',
    searchGenres: ['Romance', 'Contemporary Romance', 'Historical Romance'],
    searchMoods: ['Emotional', 'Romantic', 'Heartwarming'],
    searchQueries: ['romance contemporary', 'love story'],
    genres: [
      { name: 'Friendship', emoji: '🤝', gradient: 'linear-gradient(135deg, #ec4899, #f9a8d4)' },
      { name: 'Heart Stories', emoji: '💕', gradient: 'linear-gradient(135deg, #4a7050, #a8c4a9)' },
      { name: 'Kind Tales', emoji: '🌸', gradient: 'linear-gradient(135deg, #3b5940, #7fa882)' },
      { name: 'Best Friends', emoji: '👫', gradient: 'linear-gradient(135deg, #f472b6, #fbcfe8)' },
      { name: 'Happy Endings', emoji: '🌈', gradient: 'linear-gradient(135deg, #5f8d62, #ccdccd)' },
    ],
  },
  comfort: {
    id: 'comfort',
    name: 'The Cozy Reader',
    adventureTitle: 'THE COZY READER',
    emoji: '🌱',
    description: 'You love gentle, everyday stories that feel like home.',
    kidTagline: 'You love cozy stories about everyday life!',
    likes: ['everyday adventures', 'cozy moments', 'stories that feel like home'],
    recommendedCategories: ['📖 Everyday stories', '📖 Cozy tales', '📖 Slice of life'],
    tags: ['Cozy', 'Fiction'],
    genreLabel: 'everyday stories',
    searchGenres: ['Cozy', 'Slice of Life', 'Feel-Good'],
    searchMoods: ['Cozy', 'Heartwarming', 'Relaxing'],
    searchQueries: ['cozy fantasy', 'feel good fiction'],
    genres: [
      { name: 'Everyday Tales', emoji: '🏡', gradient: 'linear-gradient(135deg, #5f8d62, #a8c4a9)' },
      { name: 'Cozy Corner', emoji: '🍵', gradient: 'linear-gradient(135deg, #4a7050, #7fa882)' },
      { name: 'Small Town', emoji: '🌿', gradient: 'linear-gradient(135deg, #2d4330, #5f8d62)' },
      { name: 'Sunny Days', emoji: '☀️', gradient: 'linear-gradient(135deg, #fbbf24, #fde68a)' },
      { name: 'Found Family', emoji: '🤗', gradient: 'linear-gradient(135deg, #4a7050, #a8c4a9)' },
    ],
  },
  thinker: {
    id: 'thinker',
    name: 'The Star Gazer',
    adventureTitle: 'THE STAR GAZER',
    emoji: '🚀',
    description: 'You love space, science, and mind-blowing ideas!',
    kidTagline: 'You love space adventures and big ideas!',
    likes: ['space adventures', 'cool science', 'future worlds'],
    recommendedCategories: ['📖 Space adventures', '📖 Science stories', '📖 Future worlds'],
    tags: ['Sci-Fi', 'Philosophy'],
    genreLabel: 'space & science',
    searchGenres: ['Science Fiction', 'Speculative Fiction', 'Philosophy'],
    searchMoods: ['Thought-provoking', 'Dark', 'Epic'],
    searchQueries: ['science fiction', 'speculative fiction'],
    genres: [
      { name: 'Space Adventures', emoji: '🚀', gradient: 'linear-gradient(135deg, #1e3a5f, #3b82f6)' },
      { name: 'Cool Science', emoji: '🔬', gradient: 'linear-gradient(135deg, #1e2d20, #3b5940)' },
      { name: 'Future Worlds', emoji: '🌌', gradient: 'linear-gradient(135deg, #2d4330, #6366f1)' },
      { name: 'Robot Tales', emoji: '🤖', gradient: 'linear-gradient(135deg, #4b5563, #9ca3af)' },
      { name: 'What If?', emoji: '💭', gradient: 'linear-gradient(135deg, #3b5940, #5f8d62)' },
    ],
  },
  shadow: {
    id: 'shadow',
    name: 'The Brave Reader',
    adventureTitle: 'THE BRAVE READER',
    emoji: '🖤',
    description: 'You love spooky, thrilling stories that give you goosebumps!',
    kidTagline: 'You love spooky stories and brave heroes!',
    likes: ['spooky tales', 'brave heroes', 'exciting chills'],
    recommendedCategories: ['📖 Spooky stories', '📖 Brave heroes', '📖 Dark adventures'],
    tags: ['Horror', 'Dark Fantasy'],
    genreLabel: 'spooky adventures',
    searchGenres: ['Horror', 'Dark Fantasy', 'Gothic'],
    searchMoods: ['Dark', 'Creepy', 'Atmospheric'],
    searchQueries: ['horror dark fantasy', 'gothic horror'],
    genres: [
      { name: 'Spooky Tales', emoji: '👻', gradient: 'linear-gradient(135deg, #1e2d20, #374151)' },
      { name: 'Brave Heroes', emoji: '🛡️', gradient: 'linear-gradient(135deg, #2d4330, #4b5563)' },
      { name: 'Dark Castles', emoji: '🏚️', gradient: 'linear-gradient(135deg, #1e2d20, #3b5940)' },
      { name: 'Midnight Stories', emoji: '🌑', gradient: 'linear-gradient(135deg, #111827, #374151)' },
      { name: 'Monster Friends', emoji: '🧛', gradient: 'linear-gradient(135deg, #4c1d95, #7c3aed)' },
    ],
  },
  challenger: {
    id: 'challenger',
    name: 'The Story Champion',
    adventureTitle: 'THE STORY CHAMPION',
    emoji: '🔥',
    description: 'You love big feelings, tough choices, and unforgettable endings!',
    kidTagline: 'You love stories that challenge you and stick with you!',
    likes: ['big feelings', 'tough choices', 'unforgettable endings'],
    recommendedCategories: ['📖 Epic stories', '📖 Award winners', '📖 Big adventures'],
    tags: ['Literary', 'Drama'],
    genreLabel: 'epic stories',
    searchGenres: ['Literary Fiction', 'Psychological Fiction', 'Drama'],
    searchMoods: ['Emotional', 'Dark', 'Epic'],
    searchQueries: ['literary fiction award', 'psychological drama'],
    genres: [
      { name: 'Epic Stories', emoji: '📖', gradient: 'linear-gradient(135deg, #2d4330, #3b5940)' },
      { name: 'Award Winners', emoji: '🏆', gradient: 'linear-gradient(135deg, #f59e0b, #fcd34d)' },
      { name: 'Big Feelings', emoji: '🎭', gradient: 'linear-gradient(135deg, #1e2d20, #3b5940)' },
      { name: 'Plot Twists', emoji: '🌀', gradient: 'linear-gradient(135deg, #3b5940, #5f8d62)' },
      { name: 'Never Forget', emoji: '🔥', gradient: 'linear-gradient(135deg, #dc2626, #f87171)' },
    ],
  },
};

export const defaultReaderType = readerTypes.dreamer;

export function getReaderType(id: string | null | undefined): ReaderType {
  if (id && id in readerTypes) return readerTypes[id as ReaderTypeId];
  return defaultReaderType;
}
